services:
  - type: web
    name: dha-render-starter
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BASE_URL
        sync: false
      - key: PORT
        value: 10000
